"""empty message

Revision ID: 4b403bfe9b44
Revises: b6d34c917a37
Create Date: 2022-08-12 15:46:34.200785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b403bfe9b44'
down_revision = 'b6d34c917a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.drop_constraint('messages_channel_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_channel_id_fkey', 'messages', 'channels', ['channel_id'], ['id'])
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
